### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patmun/pynetdicom#2]
```
1. Not working with python 3.2, had to use with 2.7
2. Can't use SSL for DICOM connection

Do you planning to develop pynetdicom?

```

Original issue reported on code.google.com by `nixargh` on 25 May 2012 at 10:59

**Comment by naggie** [comment]
Tracked by 
https://github.com/patmun/pynetdicom/issues/38
https://github.com/patmun/pynetdicom/issues/41
