### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patmun/pynetdicom#22]
```
Incorrect indentation here: 
https://code.google.com/p/pynetdicom/source/browse/source/netdicom/applicationen
tity.py?spec=svnbcdde35b2aaea722b9c58477cee10f2d302360cc&r=bcdde35b2aaea722b9c58
477cee10f2d302360cc#327

Should look like: 
https://github.com/cancan101/pynetdicom/commit/981ec10dc8cc554d7ba7e864d932ea18a
df7a88c
```

Original issue reported on code.google.com by `agrothberg` on 19 Jan 2015 at 10:52

**Comment by naggie** [comment]
I can't find that ref anywhere, although it looks like this refers to https://github.com/patmun/pynetdicom/blob/master/netdicom/applicationentity.py#L326 . I think the implication is that logic should be outside the loop, either that or this is for old code. However, it's made fire every 50 iterations which implies it's designed to be in the loop.


Please re-open if you disagree.
