### ISSUE TITLE
Cherry-pick cancan101 Fork

### ISSUE THREAD

**Issue by cancan101** [patmun/pynetdicom#44]
You can see my changes here: https://github.com/patmun/pynetdicom/compare/master...cancan101:master

TO avoid confusion, best to ignore the `dicom` shim and the `distribute_setup.py` file.

**Comment by naggie** [comment]
@patmun How do you feel about merging this?

**Comment by patmun** [comment]
I'm not against merging: it seems to fix quite a lot of mistakes. But I have to test it.

**Comment by naggie** [comment]
Looks like it's merged. Thanks to you both
