### ISSUE TITLE
Strange Behavior in `DIMSEprovider.Receive`

### ISSUE THREAD

**Issue by cancan101** [patmun/pynetdicom#51]
Currently `DIMSEprovider.Receive` takes `Wait` and `Timeout`. If `Wait` is set to `True`, regardless of what `Timeout` is set to (`None` or an int), there is the possibility to be stuck in an spin loop indefinitely.  
As of now if the TCP connection is cut, it is possible to be stuck in this loop indefinitely which is not desirable. 

If `Wait` is set to `False` then no waiting happens regardless of what `Timeout` is set to.

**Comment by naggie** [comment]
I've fixed this in this commit https://github.com/patmun/pynetdicom/pull/49/commits/ea2c76a5da103d3845d0ac8884350130388b0510

which is part of this PR: https://github.com/patmun/pynetdicom/pull/49

**Comment by naggie** [comment]
Resolved.
